### ISSUE TITLE
[bash,nvim] При открытии плавающего терминала, виртуальное окружение перестаёт работать

### ISSUE THREAD

**Issue by Strelok-NSS** [hatkidchan/sddot#1]

**Comment by hatkidchan** [comment]
Проблема связана была с тем, что при открытии новой сессии, переменная `$PATH` определяется снова, но с немного другим порядком. У меня такой проблемы нет, возможно у тебя не bash а zsh с моим старым конфигом (https://github.com/hatkidchan/dotfiles/blob/master/zsh/dot.zshrc#L1), где, по какой-то причине у меня `/usr/bin` имеет приоритет выше, чем все остальные пути поиска. Хотфиксом является смена порядка (например, как сделано в https://github.com/hatkidchan/sddot/blob/master/bash/.config/bash/environ#L5)
